### ISSUE TITLE
vNIC performance not collected and display name cluttered with guid

### ISSUE THREAD

**Issue by brandubh** [brandubh/HypervMP#11]
Seems that vNIC perf traffic is not collected and the guid in the display name makes it ugly. Check for a different way.

**Comment by andriuskr** [comment]
+1 for vNIC performance data is not collected.

**Comment by brandubh** [comment]
Bug confirmed and identified will be fixed in the next build

**Comment by brandubh** [comment]
Fixed in version 1.1.0.70

**Comment by andriuskr** [comment]
I don't get it, how to download 1.1.0.70 version of this mp ?

**Comment by brandubh** [comment]
My fault, I didn't include the MP in the repository, you can find it on TechNet Gallery https://gallery.technet.microsoft.com/Hyper-V-2012-R2-management-2e067735

**Comment by andriuskr** [comment]
Imported updated mp, but vNIC performance traffic is not collected

**Comment by brandubh** [comment]
You need to wait a complete discovery cycle completes before perf counters get collected

**Comment by andriuskr** [comment]
waiting about 24hours

**Comment by brandubh** [comment]
Uhm if you open the discovered inventory ans filter it for "Hyper-V 2012R2 - VM NIC (QND)" you should see a property "Performance Instance Name". The bug was in discovery, the property was not set. If the property is there and the perf counters on the hyperv host are ok, the counters should be collected. See attached images.
![28-08-2015 08-40-51](https://cloud.githubusercontent.com/assets/12165412/9540589/b5922792-4d60-11e5-93f7-3fde307253b8.png)
![28-08-2015 08-42-03](https://cloud.githubusercontent.com/assets/12165412/9540590/baa3e0e0-4d60-11e5-89bf-afc7c8ae299a.png)

**Comment by andriuskr** [comment]
Sorry, my mistake. Performance data is collected.
Just looked at state, and hoped it has to change to monitored from not monitored.
