### ISSUE TITLE
Virtual Drives performance data is not collected for disks on SOFS shares

### ISSUE THREAD

**Issue by andriuskr** [brandubh/HypervMP#14]
If Virtual Drive (vhdx) is moved or placed to SOFS share, its performance data, like IOPS, Read bytes/sec, Write bytes/sec is not collected.

**Comment by brandubh** [comment]
This is a scenario that we need to investigate, but I don't have a SOFS cluster in my environment to check against. Perf counters for VHDs are collected using std performance counters. WOuld you mind to check if they exists on the hyper-v host for the vhds on SOFS shares?

**Comment by andriuskr** [comment]
I have checked and the performance counters for VHD's on SOFS shares are present on hyper-v hosts.

**Comment by andriuskr** [comment]
I have also tried to collect  Normalized Throughput performance of Virtual Machines on SOFS with Microsoft Operations Management Suite and it is working.

**Comment by andriuskr** [comment]
Hello, i am going to look back to this problem :)
Hyper-V hosts shows this error:
In PerfDataSource, could not resolve counter Hyper-V Virtual Storage Device, Normalized Throughput, --sofs1-JBOD2-VMM_Templates-VMM_Templates2008R2-Windows Server 2008 R2 SP1.vhdx. Module will not be unloaded. 

One or more workflows were affected by this.  

Workflow name: QND.Hyperv2012R2.VHDNormIOPS.Rule 
Instance name: VMM_Templates2008R2 - Hard Drive on IDE controller number 0 at location 0 
Instance ID: {D6165AD3-E35A-DB5F-2668-04FBCA3676FE} 
Management group: XXX

i think the problem is, that Rule tries to monitor bad path
 --sofs1-JBOD2-VMM_Templates-VMM_Templates2008R2-Windows Server 2008 R2 SP1.vhdx

it should be  \\sofs1\JBOD2\VMM_Templates-VMM_Templates2008R2-Windows Server 2008 R2 SP1.vhdx

Need to change somethere - with \

**Comment by mortenlerudjordet** [comment]
I would think this has more to do with the vhd being a template and has no performance counter.
The rule will fail as it expects the vhdx to have a performance counter on the SOFS, and when this not is the case it will throw an error.

**Comment by mortenlerudjordet** [comment]
The relevant code you are looking for are in the Discover-VM.ps1

$oDisk.AddProperty("$MPElement[Name='QND.HyperV.2012R2.VirtualDrive']/ImageFile$", $disk.Path)
try {$perfInstance = $disk.Path.Replace('\','-')}
catch {$perfInstance=''}	

I would guess the naming of the performance counter for the disk is not in line with what the code expects it to be.

**Comment by brandubh** [comment]
fixed as per merge from mailampert
