### ISSUE TITLE
Powershell scripts stopping due to time-out

### ISSUE THREAD

**Issue by ghost** [brandubh/HypervMP#16]
We are running Hyper-V on several Hyper-V hosts running Microsoft Windows Server 2012 R2 Datacenter (core edition). We have recent hardware, optimal tuned for performance. Xeon E5-2680 v3 @2.50 GHz, 2 sockets, 24 cores, 48 logical processors. 512 Gb RAM. On each host are running about 70 virtual machines.
 
On these systems we are having trouble getting powershell script to run within the time limit. These script are from the QND management packs.
A few examples: Discover-VM.ps1, Get-VMMeasure.ps1, GetDiskPartitionSpaceV2.ps1 and so on.
Extending the configured time-out does not help.
 
Are you aware of these kind of problems in the field?
Do you have an idea how to solve this?
 
Your help would be most appreciated.
 
Many thanks,
 
Rene Riksen
Netherlands

**Comment by brandubh** [comment]
Sorry for the super late reply, but I completely missed this one. Which error message do you have? Is the script dropped or it timeouts? In the latetr case override one of the monitors or the discovery and set tracelevel to 4. How is the CPU performing? We were notified of an issue similar to this, but in that case it was WMI related.

**Comment by ghost** [comment]
Hi Daniele,

Indeed we managed to solve our problems by increasing the WMI buffers. We suffered from script time-outs because of poor WMI performance.
Kevin Holman has a post on this matter: https://blogs.technet.microsoft.com/kevinholman/2009/06/29/getting-lots-of-script-failed-to-run-alerts-wmi-probe-failed-execution-backward-compatibility-script-error/

Thanks for your reply.

Regards,
René
